### ISSUE TITLE
Labs out of order

### ISSUE THREAD

**Issue by psan2** [learn-co-curriculum/react-events-crash-course-readme#1]
In terms of learning progression, this lab seems more appropriate before the matrix rendering lab, which calls for React events (at that stage, before they've been formally introduced).

**Comment by maxwellbenton** [comment]
Hi @psan2,

Thanks for reporting this issue. We're now aware of it and are tracking this and other ordering issues in a new issue [here](https://github.com/learn-co-curriculum/this-is-react-readme/issues/3). 

We are currently updating and restructuring the materials in this section and will add this to our internal work queue.  We will be updating the order of lessons in the next phase of this process and will take this information into consideration in upcoming releases of this curriculum.

We're closing this issue but invite you to follow the progress. We will notify
you when this issue is resolved.

Thanks for contributing!
